spring.application.name=fileuploading

#enabling multipart uploads
spring.servlet.multipart.enabled=true

#max file Size
spring.servlet.multipart.max-file-size=300MB

#threshold after which file are written in Disk
spring.servlet.multipart.file-size-threshold=1KB